# Generated by Django 5.2.9 on 2025-12-14 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('platforms', models.JSONField(default=list)),
                ('column', models.CharField(choices=[('backlog', 'Backlog'), ('content_writing', 'Content Writing'), ('design_creative', 'Design/Creative'), ('internal_review', 'Internal Review'), ('client_approval', 'Client Approval'), ('scheduled', 'Scheduled'), ('posted', 'Posted')], default='backlog', max_length=50)),
                ('package', models.CharField(choices=[('spark', 'Spark'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='spark', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revise_needed', 'Revise Needed')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content_items', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
