# Generated by Django 5.2.9 on 2025-12-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_historicalcontentitem'),
        ('invoice', '0003_businessinfo_secondary_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_content_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_content_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Image'), ('carousel', 'Carousel'), ('reel', 'Reel / Video'), ('story', 'Story'), ('cover', 'Cover'), ('banner', 'Banner'), ('flyer', 'Flyer'), ('logo', 'Logo'), ('package_design', 'Package Design')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='external_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='is_carousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='platform_caption_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='post_action',
            field=models.CharField(choices=[('instant', 'Instant Post'), ('schedule', 'Schedule Post'), ('manual', 'Manual Posting')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='post_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='post_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='revise_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='revise_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='revise_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='column',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('content_writing', 'Content Writing'), ('design_creative', 'Design/Creative'), ('internal_review', 'Internal Review'), ('client_approval', 'Client Approval'), ('ready', 'Ready to Post'), ('scheduled', 'Scheduled'), ('posted', 'Posted')], default='backlog', max_length=50),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='content_media/')),
                ('public_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='kanban.contentitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaLocationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('raw_response', models.JSONField()),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='metalocationcache',
            index=models.Index(fields=['name'], name='kanban_metal_name_5f5bb1_idx'),
        ),

        # --- keep simple_history table in sync ---
        migrations.AddField(
            model_name='historicalcontentitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='content_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Image'), ('carousel', 'Carousel'), ('reel', 'Reel / Video'), ('story', 'Story'), ('cover', 'Cover'), ('banner', 'Banner'), ('flyer', 'Flyer'), ('logo', 'Logo'), ('package_design', 'Package Design')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='external_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='is_carousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='platform_caption_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='post_action',
            field=models.CharField(choices=[('instant', 'Instant Post'), ('schedule', 'Schedule Post'), ('manual', 'Manual Posting')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='post_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='post_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='revise_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='revise_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='revise_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontentitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcontentitem',
            name='column',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('content_writing', 'Content Writing'), ('design_creative', 'Design/Creative'), ('internal_review', 'Internal Review'), ('client_approval', 'Client Approval'), ('ready', 'Ready to Post'), ('scheduled', 'Scheduled'), ('posted', 'Posted')], default='backlog', max_length=50),
        ),
    ]
