# Generated by Django 5.2.9 on 2025-12-21 20:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_historicalmediaasset_historicalmetalocationcache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='column',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('content_writing', 'Content Writing'), ('design_creative', 'Design/Creative'), ('internal_review', 'Internal Review'), ('client_approval', 'Client Approval'), ('finalized', 'Finalized'), ('ready', 'Ready to Post'), ('scheduled', 'Scheduled'), ('posted', 'Posted')], default='backlog', max_length=50),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcontentitem',
            name='column',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('content_writing', 'Content Writing'), ('design_creative', 'Design/Creative'), ('internal_review', 'Internal Review'), ('client_approval', 'Client Approval'), ('finalized', 'Finalized'), ('ready', 'Ready to Post'), ('scheduled', 'Scheduled'), ('posted', 'Posted')], default='backlog', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcontentitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('client', 'Client'), ('agency', 'Agency')], max_length=10)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kanban.contentitem')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='kanban.contentcomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContentComment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('archived', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('client', 'Client'), ('agency', 'Agency')], max_length=10)),
                ('text', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kanban.contentitem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kanban.contentcomment')),
            ],
            options={
                'verbose_name': 'historical content comment',
                'verbose_name_plural': 'historical content comments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
