# Generated by Django 5.2.9 on 2025-12-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_contentitem_column_alter_contentitem_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentitem',
            old_name='description',
            new_name='creative_copy',
        ),
        migrations.RenameField(
            model_name='contentitem',
            old_name='caption',
            new_name='post_caption',
        ),
        migrations.RenameField(
            model_name='historicalcontentitem',
            old_name='description',
            new_name='creative_copy',
        ),
        migrations.RenameField(
            model_name='historicalcontentitem',
            old_name='caption',
            new_name='post_caption',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='package',
        ),
        migrations.RemoveField(
            model_name='historicalcontentitem',
            name='package',
        ),
    ]
