# Generated by Django 5.2.9 on 2025-12-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_historicalcontentitemcommentread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcontentitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
