# Generated by Django 5.2.9 on 2025-12-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaaccesstoken',
            name='meta_user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='metaaccesstoken',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
