# Generated by Django 5.2.9 on 2025-12-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_clientprofile_contact_person_and_more'),
        ('meta', '0002_metaaccesstoken_meta_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpagemapping',
            name='client_id',
        ),
        migrations.AddField(
            model_name='clientpagemapping',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='page_mappings', to='core.clientprofile'),
            preserve_default=False,
        ),
    ]
