# Generated by Django 5.2.9 on 2025-12-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
