# Generated by Django 5.2.9 on 2025-12-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_submissions'),
        ('home', '0002_testimonial_profile_pic'),
    ]

    operations = [
    ]
