# Generated by Django 4.2.27 on 2025-12-16 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalclientprofile_historicalcustomuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact_whatsapp',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='historicalclientprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='historicalclientprofile',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='historicalclientprofile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='historicalclientprofile',
            name='contact_whatsapp',
        ),
        migrations.RemoveField(
            model_name='historicalclientprofile',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='historicalclientprofile',
            name='salutation',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='business_phone_country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Mx', 'Mx')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclientprofile',
            name='business_phone_country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='historicalclientprofile',
            name='contact_person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Mx', 'Mx')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='whatsapp_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='hsn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hsn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
