# Generated by Django 4.2.27 on 2025-12-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicecategory_historicalservicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='client_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalclientprofile',
            name='client_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
    ]
