# Generated by Django 5.2.9 on 2025-12-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientprofile_client_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='historicalclientprofile',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='historicalclientprofile',
            name='designation',
        ),
    ]
