# Generated by Django 5.2.9 on 2025-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_clientprofile_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='pending_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='pending_contact_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclientprofile',
            name='pending_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalclientprofile',
            name='pending_contact_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
