# Generated by Django 5.2.9 on 2025-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clientprofile_pending_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='is_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='pipeline_config',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='is_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='pipeline_config',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
