# Generated by Django 5.2.9 on 2025-12-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicaldevicetoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
