# Generated by Django 5.2.9 on 2025-12-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_service_category_alter_service_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='service_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
