# Generated by Django 5.2.9 on 2025-12-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_historicalservice_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='other_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='other_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
