# Generated by Copilot on 2025-12-23

from django.db import migrations


class Migration(migrations.Migration):
    """No-op schema migration.

    This migration documents the change in `CustomUser.type` choices to include
    the new value: `editor`.

    Note: `choices` changes do not affect the database schema; they affect
    validation/forms/admin only.
    """

    dependencies = [
        ("core", "0013_historicalservice_other_platform_and_more"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
