# Generated by Django 5.2.9 on 2025-12-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_editor_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('superadmin', 'Superadmin'), ('manager', 'Manager'), ('content_writer', 'Content Writer'), ('designer', 'Designer'), ('editor', 'Editor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('superadmin', 'Superadmin'), ('manager', 'Manager'), ('content_writer', 'Content Writer'), ('designer', 'Designer'), ('editor', 'Editor')], max_length=20),
        ),
    ]
