# Generated by Django 5.2.9 on 2025-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_businessinfo_paymentmode_paymentterm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusinessinfo',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
