# Generated by Django 5.2.9 on 2025-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_businessinfo_secondary_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
