# Generated by Django 5.2.9 on 2025-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_historicalinvoice_start_date_invoice_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
