# Generated by Django 5.2.9 on 2025-12-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_historicalbusinessinfo_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusinessinfo',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
