# Generated by Django 5.2.9 on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_businessinfo_address_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
